services:
  calou:
    build: .
    container_name: calou
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - METEO_JSON_PATH=/data/meteo.json
    volumes:
      - /home/sylvain/collecte-netatmo/meteo.json:/data/meteo.json:ro
    expose:
      - "8000"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true